<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'AppBundle\Custom\MyController' shared autowired service.

return $this->services['AppBundle\Custom\MyController'] = new \AppBundle\Custom\MyController();
