<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerC0v69zu\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerC0v69zu/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerC0v69zu.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerC0v69zu\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerC0v69zu\appDevDebugProjectContainer(array(
    'container.build_hash' => 'C0v69zu',
    'container.build_id' => '7406804f',
    'container.build_time' => 1521429658,
));
