<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOxwpu5z\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOxwpu5z/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerOxwpu5z.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerOxwpu5z\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerOxwpu5z\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Oxwpu5z',
    'container.build_id' => '47dacc78',
    'container.build_time' => 1521512925,
));
